theme: minima
title: theranos fan club
author: srivalli
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  i love u lizzy! 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
